[package]
name = "fastdl"
version = "0.1.0"
authors = ["Byeonggon Lee <gonny952@gmail.com>"]

[dependencies]
libloading = "^0.5"

[dev-dependencies]
[dev-dependencies.dylibexample]
path = "dylibexample"
version = "^0.1.0"

